;;;; Generated on 9/21/2017 at 11:42:02 (UTC-8).

(COMMON-LISP:IN-PACKAGE #:MAGICL.EXPOKIT-CFFI)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%DGPADM))

(CFFI:DEFCFUN ("dgpadm_" %%DGPADM :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (IDEG :POINTER)
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (WSP :POINTER)
  (LWSP :POINTER)
  (IPIV :POINTER)
  (IEXPH :POINTER)
  (NS :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%DGPADM))

(COMMON-LISP:PUSHNEW '("DGPADM" "dgpadm_" %%DGPADM %DGPADM)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %DGPADM))

(COMMON-LISP:DEFUN %DGPADM (IDEG M T H LDH WSP LWSP IPIV IEXPH NS IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DGPADM)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IDEG)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT)
                        WSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LWSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32))
                        IPIV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IEXPH)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) NS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((IDEG-REF72009 ':INT32) (M-REF72010 ':INT32)
                              (T-REF72011 ':DOUBLE) (LDH-REF72013 ':INT32)
                              (LWSP-REF72015 ':INT32) (IEXPH-REF72017 ':INT32)
                              (NS-REF72018 ':INT32) (IFLAG-REF72019 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF IDEG-REF72009 :INT32) IDEG)
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF72010 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF72011 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF72013 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF LWSP-REF72015 :INT32) LWSP)
    (COMMON-LISP:SETF (CFFI:MEM-REF IEXPH-REF72017 :INT32) IEXPH)
    (COMMON-LISP:SETF (CFFI:MEM-REF NS-REF72018 :INT32) NS)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF72019 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF72012 H) (WSP-REF72014 WSP)
                                            (IPIV-REF72016 IPIV))
      (%%DGPADM IDEG-REF72009 M-REF72010 T-REF72011 H-REF72012 LDH-REF72013
       WSP-REF72014 LWSP-REF72015 IPIV-REF72016 IEXPH-REF72017 NS-REF72018
       IFLAG-REF72019))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %DGPADM))

(COMMON-LISP:EXPORT '%DGPADM '#:MAGICL.EXPOKIT-CFFI)


(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%DSPADM))

(CFFI:DEFCFUN ("dspadm_" %%DSPADM :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (IDEG :POINTER)
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (WSP :POINTER)
  (LWSP :POINTER)
  (IPIV :POINTER)
  (IEXPH :POINTER)
  (NS :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%DSPADM))

(COMMON-LISP:PUSHNEW '("DSPADM" "dspadm_" %%DSPADM %DSPADM)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %DSPADM))

(COMMON-LISP:DEFUN %DSPADM (IDEG M T H LDH WSP LWSP IPIV IEXPH NS IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DSPADM)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IDEG)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT)
                        WSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LWSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32))
                        IPIV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IEXPH)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) NS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((IDEG-REF72020 ':INT32) (M-REF72021 ':INT32)
                              (T-REF72022 ':DOUBLE) (LDH-REF72024 ':INT32)
                              (LWSP-REF72026 ':INT32) (IEXPH-REF72028 ':INT32)
                              (NS-REF72029 ':INT32) (IFLAG-REF72030 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF IDEG-REF72020 :INT32) IDEG)
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF72021 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF72022 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF72024 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF LWSP-REF72026 :INT32) LWSP)
    (COMMON-LISP:SETF (CFFI:MEM-REF IEXPH-REF72028 :INT32) IEXPH)
    (COMMON-LISP:SETF (CFFI:MEM-REF NS-REF72029 :INT32) NS)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF72030 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF72023 H) (WSP-REF72025 WSP)
                                            (IPIV-REF72027 IPIV))
      (%%DSPADM IDEG-REF72020 M-REF72021 T-REF72022 H-REF72023 LDH-REF72024
       WSP-REF72025 LWSP-REF72026 IPIV-REF72027 IEXPH-REF72028 NS-REF72029
       IFLAG-REF72030))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %DSPADM))

(COMMON-LISP:EXPORT '%DSPADM '#:MAGICL.EXPOKIT-CFFI)


(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%ZGPADM))

(CFFI:DEFCFUN ("zgpadm_" %%ZGPADM :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (IDEG :POINTER)
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (WSP :POINTER)
  (LWSP :POINTER)
  (IPIV :POINTER)
  (IEXPH :POINTER)
  (NS :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%ZGPADM))

(COMMON-LISP:PUSHNEW '("ZGPADM" "zgpadm_" %%ZGPADM %ZGPADM)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %ZGPADM))

(COMMON-LISP:DEFUN %ZGPADM (IDEG M T H LDH WSP LWSP IPIV IEXPH NS IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZGPADM)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IDEG)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT))
                        H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT))
                        WSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LWSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32))
                        IPIV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IEXPH)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) NS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((IDEG-REF72031 ':INT32) (M-REF72032 ':INT32)
                              (T-REF72033 ':DOUBLE) (LDH-REF72035 ':INT32)
                              (LWSP-REF72037 ':INT32) (IEXPH-REF72039 ':INT32)
                              (NS-REF72040 ':INT32) (IFLAG-REF72041 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF IDEG-REF72031 :INT32) IDEG)
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF72032 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF72033 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF72035 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF LWSP-REF72037 :INT32) LWSP)
    (COMMON-LISP:SETF (CFFI:MEM-REF IEXPH-REF72039 :INT32) IEXPH)
    (COMMON-LISP:SETF (CFFI:MEM-REF NS-REF72040 :INT32) NS)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF72041 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF72034 H) (WSP-REF72036 WSP)
                                            (IPIV-REF72038 IPIV))
      (%%ZGPADM IDEG-REF72031 M-REF72032 T-REF72033 H-REF72034 LDH-REF72035
       WSP-REF72036 LWSP-REF72037 IPIV-REF72038 IEXPH-REF72039 NS-REF72040
       IFLAG-REF72041))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %ZGPADM))

(COMMON-LISP:EXPORT '%ZGPADM '#:MAGICL.EXPOKIT-CFFI)


(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%ZHPADM))

(CFFI:DEFCFUN ("zhpadm_" %%ZHPADM :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (IDEG :POINTER)
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (WSP :POINTER)
  (LWSP :POINTER)
  (IPIV :POINTER)
  (IEXPH :POINTER)
  (NS :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%ZHPADM))

(COMMON-LISP:PUSHNEW '("ZHPADM" "zhpadm_" %%ZHPADM %ZHPADM)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %ZHPADM))

(COMMON-LISP:DEFUN %ZHPADM (IDEG M T H LDH WSP LWSP IPIV IEXPH NS IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZHPADM)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IDEG)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT))
                        H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT))
                        WSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LWSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32))
                        IPIV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IEXPH)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) NS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((IDEG-REF72042 ':INT32) (M-REF72043 ':INT32)
                              (T-REF72044 ':DOUBLE) (LDH-REF72046 ':INT32)
                              (LWSP-REF72048 ':INT32) (IEXPH-REF72050 ':INT32)
                              (NS-REF72051 ':INT32) (IFLAG-REF72052 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF IDEG-REF72042 :INT32) IDEG)
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF72043 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF72044 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF72046 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF LWSP-REF72048 :INT32) LWSP)
    (COMMON-LISP:SETF (CFFI:MEM-REF IEXPH-REF72050 :INT32) IEXPH)
    (COMMON-LISP:SETF (CFFI:MEM-REF NS-REF72051 :INT32) NS)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF72052 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF72045 H) (WSP-REF72047 WSP)
                                            (IPIV-REF72049 IPIV))
      (%%ZHPADM IDEG-REF72042 M-REF72043 T-REF72044 H-REF72045 LDH-REF72046
       WSP-REF72047 LWSP-REF72048 IPIV-REF72049 IEXPH-REF72050 NS-REF72051
       IFLAG-REF72052))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %ZHPADM))

(COMMON-LISP:EXPORT '%ZHPADM '#:MAGICL.EXPOKIT-CFFI)


(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%DGCHBV))

(CFFI:DEFCFUN ("dgchbv_" %%DGCHBV :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (Y :POINTER)
  (WSP :POINTER)
  (IWSP :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%DGCHBV))

(COMMON-LISP:PUSHNEW '("DGCHBV" "dgchbv_" %%DGCHBV %DGCHBV)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %DGCHBV))

(COMMON-LISP:DEFUN %DGCHBV (M T H LDH Y WSP IWSP IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DGCHBV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) Y)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT))
                        WSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32))
                        IWSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF72053 ':INT32) (T-REF72054 ':DOUBLE)
                              (LDH-REF72056 ':INT32) (IFLAG-REF72060 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF72053 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF72054 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF72056 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF72060 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF72055 H) (Y-REF72057 Y)
                                            (WSP-REF72058 WSP)
                                            (IWSP-REF72059 IWSP))
      (%%DGCHBV M-REF72053 T-REF72054 H-REF72055 LDH-REF72056 Y-REF72057
       WSP-REF72058 IWSP-REF72059 IFLAG-REF72060))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %DGCHBV))

(COMMON-LISP:EXPORT '%DGCHBV '#:MAGICL.EXPOKIT-CFFI)


(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%DNCHBV))

(CFFI:DEFCFUN ("dnchbv_" %%DNCHBV :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (Y :POINTER)
  (WSP :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%DNCHBV))

(COMMON-LISP:PUSHNEW '("DNCHBV" "dnchbv_" %%DNCHBV %DNCHBV)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %DNCHBV))

(COMMON-LISP:DEFUN %DNCHBV (M T H LDH Y WSP)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DNCHBV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) Y)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT))
                        WSP))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF72061 ':INT32) (T-REF72062 ':DOUBLE)
                              (LDH-REF72064 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF72061 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF72062 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF72064 :INT32) LDH)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF72063 H) (Y-REF72065 Y)
                                            (WSP-REF72066 WSP))
      (%%DNCHBV M-REF72061 T-REF72062 H-REF72063 LDH-REF72064 Y-REF72065
       WSP-REF72066))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %DNCHBV))

(COMMON-LISP:EXPORT '%DNCHBV '#:MAGICL.EXPOKIT-CFFI)


(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%DSCHBV))

(CFFI:DEFCFUN ("dschbv_" %%DSCHBV :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (Y :POINTER)
  (WSP :POINTER)
  (IWSP :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%DSCHBV))

(COMMON-LISP:PUSHNEW '("DSCHBV" "dschbv_" %%DSCHBV %DSCHBV)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %DSCHBV))

(COMMON-LISP:DEFUN %DSCHBV (M T H LDH Y WSP IWSP IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DSCHBV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) Y)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT))
                        WSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32))
                        IWSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF72067 ':INT32) (T-REF72068 ':DOUBLE)
                              (LDH-REF72070 ':INT32) (IFLAG-REF72074 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF72067 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF72068 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF72070 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF72074 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF72069 H) (Y-REF72071 Y)
                                            (WSP-REF72072 WSP)
                                            (IWSP-REF72073 IWSP))
      (%%DSCHBV M-REF72067 T-REF72068 H-REF72069 LDH-REF72070 Y-REF72071
       WSP-REF72072 IWSP-REF72073 IFLAG-REF72074))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %DSCHBV))

(COMMON-LISP:EXPORT '%DSCHBV '#:MAGICL.EXPOKIT-CFFI)


(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%ZGCHBV))

(CFFI:DEFCFUN ("zgchbv_" %%ZGCHBV :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (Y :POINTER)
  (WSP :POINTER)
  (IWSP :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%ZGCHBV))

(COMMON-LISP:PUSHNEW '("ZGCHBV" "zgchbv_" %%ZGCHBV %ZGCHBV)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %ZGCHBV))

(COMMON-LISP:DEFUN %ZGCHBV (M T H LDH Y WSP IWSP IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZGCHBV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT))
                        H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT))
                        Y)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT))
                        WSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32))
                        IWSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF72075 ':INT32) (T-REF72076 ':DOUBLE)
                              (LDH-REF72078 ':INT32) (IFLAG-REF72082 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF72075 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF72076 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF72078 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF72082 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF72077 H) (Y-REF72079 Y)
                                            (WSP-REF72080 WSP)
                                            (IWSP-REF72081 IWSP))
      (%%ZGCHBV M-REF72075 T-REF72076 H-REF72077 LDH-REF72078 Y-REF72079
       WSP-REF72080 IWSP-REF72081 IFLAG-REF72082))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %ZGCHBV))

(COMMON-LISP:EXPORT '%ZGCHBV '#:MAGICL.EXPOKIT-CFFI)


(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%ZNCHBV))

(CFFI:DEFCFUN ("znchbv_" %%ZNCHBV :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (Y :POINTER)
  (WSP :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%ZNCHBV))

(COMMON-LISP:PUSHNEW '("ZNCHBV" "znchbv_" %%ZNCHBV %ZNCHBV)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %ZNCHBV))

(COMMON-LISP:DEFUN %ZNCHBV (M T H LDH Y WSP)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZNCHBV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT))
                        H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT))
                        Y)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT))
                        WSP))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF72083 ':INT32) (T-REF72084 ':DOUBLE)
                              (LDH-REF72086 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF72083 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF72084 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF72086 :INT32) LDH)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF72085 H) (Y-REF72087 Y)
                                            (WSP-REF72088 WSP))
      (%%ZNCHBV M-REF72083 T-REF72084 H-REF72085 LDH-REF72086 Y-REF72087
       WSP-REF72088))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %ZNCHBV))

(COMMON-LISP:EXPORT '%ZNCHBV '#:MAGICL.EXPOKIT-CFFI)


;;; End of file.
