;;;; Generated on 9/23/2017 at 12:17:59 (UTC-8).

(COMMON-LISP:DECLAIM
 (COMMON-LISP:OPTIMIZE (COMMON-LISP:SPEED 0) COMMON-LISP:SAFETY
  COMMON-LISP:DEBUG))

(COMMON-LISP:IN-PACKAGE #:MAGICL.EXPOKIT-CFFI)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%DGPADM))

(CFFI:DEFCFUN ("dgpadm_" %%DGPADM :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (IDEG :POINTER)
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (WSP :POINTER)
  (LWSP :POINTER)
  (IPIV :POINTER)
  (IEXPH :POINTER)
  (NS :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%DGPADM))

(COMMON-LISP:PUSHNEW '("DGPADM" "dgpadm_" %%DGPADM %DGPADM)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %DGPADM))

(COMMON-LISP:DEFUN %DGPADM (IDEG M T H LDH WSP LWSP IPIV IEXPH NS IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DGPADM)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IDEG)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT)
                        WSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LWSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32)
                         (COMMON-LISP:*))
                        IPIV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IEXPH)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) NS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((IDEG-REF71929 ':INT32) (M-REF71930 ':INT32)
                              (T-REF71931 ':DOUBLE) (LDH-REF71933 ':INT32)
                              (LWSP-REF71935 ':INT32) (IEXPH-REF71937 ':INT32)
                              (NS-REF71938 ':INT32) (IFLAG-REF71939 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF IDEG-REF71929 :INT32) IDEG)
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF71930 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF71931 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF71933 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF LWSP-REF71935 :INT32) LWSP)
    (COMMON-LISP:SETF (CFFI:MEM-REF IEXPH-REF71937 :INT32) IEXPH)
    (COMMON-LISP:SETF (CFFI:MEM-REF NS-REF71938 :INT32) NS)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF71939 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS
     ((H-REF71932 H) (WSP-REF71934 WSP) (IPIV-REF71936 IPIV))
     (%%DGPADM IDEG-REF71929 M-REF71930 T-REF71931 H-REF71932 LDH-REF71933
      WSP-REF71934 LWSP-REF71935 IPIV-REF71936 IEXPH-REF71937 NS-REF71938
      IFLAG-REF71939))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %DGPADM))

(COMMON-LISP:EXPORT '%DGPADM '#:MAGICL.EXPOKIT-CFFI)


(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%DSPADM))

(CFFI:DEFCFUN ("dspadm_" %%DSPADM :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (IDEG :POINTER)
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (WSP :POINTER)
  (LWSP :POINTER)
  (IPIV :POINTER)
  (IEXPH :POINTER)
  (NS :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%DSPADM))

(COMMON-LISP:PUSHNEW '("DSPADM" "dspadm_" %%DSPADM %DSPADM)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %DSPADM))

(COMMON-LISP:DEFUN %DSPADM (IDEG M T H LDH WSP LWSP IPIV IEXPH NS IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DSPADM)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IDEG)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT)
                        WSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LWSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32)
                         (COMMON-LISP:*))
                        IPIV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IEXPH)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) NS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((IDEG-REF71940 ':INT32) (M-REF71941 ':INT32)
                              (T-REF71942 ':DOUBLE) (LDH-REF71944 ':INT32)
                              (LWSP-REF71946 ':INT32) (IEXPH-REF71948 ':INT32)
                              (NS-REF71949 ':INT32) (IFLAG-REF71950 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF IDEG-REF71940 :INT32) IDEG)
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF71941 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF71942 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF71944 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF LWSP-REF71946 :INT32) LWSP)
    (COMMON-LISP:SETF (CFFI:MEM-REF IEXPH-REF71948 :INT32) IEXPH)
    (COMMON-LISP:SETF (CFFI:MEM-REF NS-REF71949 :INT32) NS)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF71950 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS
     ((H-REF71943 H) (WSP-REF71945 WSP) (IPIV-REF71947 IPIV))
     (%%DSPADM IDEG-REF71940 M-REF71941 T-REF71942 H-REF71943 LDH-REF71944
      WSP-REF71945 LWSP-REF71946 IPIV-REF71947 IEXPH-REF71948 NS-REF71949
      IFLAG-REF71950))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %DSPADM))

(COMMON-LISP:EXPORT '%DSPADM '#:MAGICL.EXPOKIT-CFFI)


(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%ZGPADM))

(CFFI:DEFCFUN ("zgpadm_" %%ZGPADM :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (IDEG :POINTER)
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (WSP :POINTER)
  (LWSP :POINTER)
  (IPIV :POINTER)
  (IEXPH :POINTER)
  (NS :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%ZGPADM))

(COMMON-LISP:PUSHNEW '("ZGPADM" "zgpadm_" %%ZGPADM %ZGPADM)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %ZGPADM))

(COMMON-LISP:DEFUN %ZGPADM (IDEG M T H LDH WSP LWSP IPIV IEXPH NS IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZGPADM)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IDEG)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        WSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LWSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32)
                         (COMMON-LISP:*))
                        IPIV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IEXPH)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) NS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((IDEG-REF71951 ':INT32) (M-REF71952 ':INT32)
                              (T-REF71953 ':DOUBLE) (LDH-REF71955 ':INT32)
                              (LWSP-REF71957 ':INT32) (IEXPH-REF71959 ':INT32)
                              (NS-REF71960 ':INT32) (IFLAG-REF71961 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF IDEG-REF71951 :INT32) IDEG)
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF71952 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF71953 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF71955 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF LWSP-REF71957 :INT32) LWSP)
    (COMMON-LISP:SETF (CFFI:MEM-REF IEXPH-REF71959 :INT32) IEXPH)
    (COMMON-LISP:SETF (CFFI:MEM-REF NS-REF71960 :INT32) NS)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF71961 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS
     ((H-REF71954 H) (WSP-REF71956 WSP) (IPIV-REF71958 IPIV))
     (%%ZGPADM IDEG-REF71951 M-REF71952 T-REF71953 H-REF71954 LDH-REF71955
      WSP-REF71956 LWSP-REF71957 IPIV-REF71958 IEXPH-REF71959 NS-REF71960
      IFLAG-REF71961))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %ZGPADM))

(COMMON-LISP:EXPORT '%ZGPADM '#:MAGICL.EXPOKIT-CFFI)


(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%ZHPADM))

(CFFI:DEFCFUN ("zhpadm_" %%ZHPADM :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (IDEG :POINTER)
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (WSP :POINTER)
  (LWSP :POINTER)
  (IPIV :POINTER)
  (IEXPH :POINTER)
  (NS :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%ZHPADM))

(COMMON-LISP:PUSHNEW '("ZHPADM" "zhpadm_" %%ZHPADM %ZHPADM)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %ZHPADM))

(COMMON-LISP:DEFUN %ZHPADM (IDEG M T H LDH WSP LWSP IPIV IEXPH NS IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZHPADM)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IDEG)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        WSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LWSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32)
                         (COMMON-LISP:*))
                        IPIV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IEXPH)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) NS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((IDEG-REF71962 ':INT32) (M-REF71963 ':INT32)
                              (T-REF71964 ':DOUBLE) (LDH-REF71966 ':INT32)
                              (LWSP-REF71968 ':INT32) (IEXPH-REF71970 ':INT32)
                              (NS-REF71971 ':INT32) (IFLAG-REF71972 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF IDEG-REF71962 :INT32) IDEG)
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF71963 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF71964 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF71966 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF LWSP-REF71968 :INT32) LWSP)
    (COMMON-LISP:SETF (CFFI:MEM-REF IEXPH-REF71970 :INT32) IEXPH)
    (COMMON-LISP:SETF (CFFI:MEM-REF NS-REF71971 :INT32) NS)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF71972 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS
     ((H-REF71965 H) (WSP-REF71967 WSP) (IPIV-REF71969 IPIV))
     (%%ZHPADM IDEG-REF71962 M-REF71963 T-REF71964 H-REF71965 LDH-REF71966
      WSP-REF71967 LWSP-REF71968 IPIV-REF71969 IEXPH-REF71970 NS-REF71971
      IFLAG-REF71972))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %ZHPADM))

(COMMON-LISP:EXPORT '%ZHPADM '#:MAGICL.EXPOKIT-CFFI)


(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%DGCHBV))

(CFFI:DEFCFUN ("dgchbv_" %%DGCHBV :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (Y :POINTER)
  (WSP :POINTER)
  (IWSP :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%DGCHBV))

(COMMON-LISP:PUSHNEW '("DGCHBV" "dgchbv_" %%DGCHBV %DGCHBV)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %DGCHBV))

(COMMON-LISP:DEFUN %DGCHBV (M T H LDH Y WSP IWSP IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DGCHBV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) Y)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        WSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32)
                         (COMMON-LISP:*))
                        IWSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF71973 ':INT32) (T-REF71974 ':DOUBLE)
                              (LDH-REF71976 ':INT32) (IFLAG-REF71980 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF71973 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF71974 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF71976 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF71980 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS
     ((H-REF71975 H) (Y-REF71977 Y) (WSP-REF71978 WSP) (IWSP-REF71979 IWSP))
     (%%DGCHBV M-REF71973 T-REF71974 H-REF71975 LDH-REF71976 Y-REF71977
      WSP-REF71978 IWSP-REF71979 IFLAG-REF71980))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %DGCHBV))

(COMMON-LISP:EXPORT '%DGCHBV '#:MAGICL.EXPOKIT-CFFI)


(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%DNCHBV))

(CFFI:DEFCFUN ("dnchbv_" %%DNCHBV :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (Y :POINTER)
  (WSP :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%DNCHBV))

(COMMON-LISP:PUSHNEW '("DNCHBV" "dnchbv_" %%DNCHBV %DNCHBV)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %DNCHBV))

(COMMON-LISP:DEFUN %DNCHBV (M T H LDH Y WSP)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DNCHBV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) Y)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        WSP))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF71981 ':INT32) (T-REF71982 ':DOUBLE)
                              (LDH-REF71984 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF71981 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF71982 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF71984 :INT32) LDH)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS
     ((H-REF71983 H) (Y-REF71985 Y) (WSP-REF71986 WSP))
     (%%DNCHBV M-REF71981 T-REF71982 H-REF71983 LDH-REF71984 Y-REF71985
      WSP-REF71986))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %DNCHBV))

(COMMON-LISP:EXPORT '%DNCHBV '#:MAGICL.EXPOKIT-CFFI)


(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%DSCHBV))

(CFFI:DEFCFUN ("dschbv_" %%DSCHBV :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (Y :POINTER)
  (WSP :POINTER)
  (IWSP :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%DSCHBV))

(COMMON-LISP:PUSHNEW '("DSCHBV" "dschbv_" %%DSCHBV %DSCHBV)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %DSCHBV))

(COMMON-LISP:DEFUN %DSCHBV (M T H LDH Y WSP IWSP IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DSCHBV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) Y)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        WSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32)
                         (COMMON-LISP:*))
                        IWSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF71987 ':INT32) (T-REF71988 ':DOUBLE)
                              (LDH-REF71990 ':INT32) (IFLAG-REF71994 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF71987 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF71988 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF71990 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF71994 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS
     ((H-REF71989 H) (Y-REF71991 Y) (WSP-REF71992 WSP) (IWSP-REF71993 IWSP))
     (%%DSCHBV M-REF71987 T-REF71988 H-REF71989 LDH-REF71990 Y-REF71991
      WSP-REF71992 IWSP-REF71993 IFLAG-REF71994))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %DSCHBV))

(COMMON-LISP:EXPORT '%DSCHBV '#:MAGICL.EXPOKIT-CFFI)


(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%ZGCHBV))

(CFFI:DEFCFUN ("zgchbv_" %%ZGCHBV :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (Y :POINTER)
  (WSP :POINTER)
  (IWSP :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%ZGCHBV))

(COMMON-LISP:PUSHNEW '("ZGCHBV" "zgchbv_" %%ZGCHBV %ZGCHBV)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %ZGCHBV))

(COMMON-LISP:DEFUN %ZGCHBV (M T H LDH Y WSP IWSP IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZGCHBV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        Y)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        WSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32)
                         (COMMON-LISP:*))
                        IWSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF71995 ':INT32) (T-REF71996 ':DOUBLE)
                              (LDH-REF71998 ':INT32) (IFLAG-REF72002 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF71995 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF71996 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF71998 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF72002 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS
     ((H-REF71997 H) (Y-REF71999 Y) (WSP-REF72000 WSP) (IWSP-REF72001 IWSP))
     (%%ZGCHBV M-REF71995 T-REF71996 H-REF71997 LDH-REF71998 Y-REF71999
      WSP-REF72000 IWSP-REF72001 IFLAG-REF72002))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %ZGCHBV))

(COMMON-LISP:EXPORT '%ZGCHBV '#:MAGICL.EXPOKIT-CFFI)


(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %%ZNCHBV))

(CFFI:DEFCFUN ("znchbv_" %%ZNCHBV :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
    :VOID
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (Y :POINTER)
  (WSP :POINTER))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %%ZNCHBV))

(COMMON-LISP:PUSHNEW '("ZNCHBV" "znchbv_" %%ZNCHBV %ZNCHBV)
                     (COMMON-LISP:GETF
                      (COMMON-LISP:SYMBOL-PLIST
                       'MAGICL.FOREIGN-LIBRARIES:LIBEXPOKIT)
                      ':MAGICL)
                     :TEST 'COMMON-LISP:EQUAL :KEY 'COMMON-LISP:CAR)

(COMMON-LISP:DECLAIM (COMMON-LISP:INLINE %ZNCHBV))

(COMMON-LISP:DEFUN %ZNCHBV (M T H LDH Y WSP)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZNCHBV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        Y)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        WSP))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF72003 ':INT32) (T-REF72004 ':DOUBLE)
                              (LDH-REF72006 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF72003 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF72004 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF72006 :INT32) LDH)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS
     ((H-REF72005 H) (Y-REF72007 Y) (WSP-REF72008 WSP))
     (%%ZNCHBV M-REF72003 T-REF72004 H-REF72005 LDH-REF72006 Y-REF72007
      WSP-REF72008))))

(COMMON-LISP:DECLAIM (COMMON-LISP:NOTINLINE %ZNCHBV))

(COMMON-LISP:EXPORT '%ZNCHBV '#:MAGICL.EXPOKIT-CFFI)


;;; End of file.
