;;;; Generated on 7/30/2024 at 20:38:55 (UTC-8).

(COMMON-LISP:DECLAIM
 (COMMON-LISP:OPTIMIZE (COMMON-LISP:SPEED 0) COMMON-LISP:SAFETY
  COMMON-LISP:DEBUG COMMON-LISP:COMPILATION-SPEED))

(COMMON-LISP:IN-PACKAGE #:MAGICL.BLAS-CFFI)

(COMMON-LISP:DECLAIM
 (COMMON-LISP:INLINE %%CAXPY %CAXPY %%CGEMM %CGEMM %%CGEMV %CGEMV %%CSCAL
  %CSCAL %%CSSCAL %CSSCAL %%DAXPY %DAXPY %%DGEMM %DGEMM %%DGEMV %DGEMV %%DSCAL
  %DSCAL %%SAXPY %SAXPY %%SGEMM %SGEMM %%SGEMV %SGEMV %%SSCAL %SSCAL %%ZAXPY
  %ZAXPY %%ZDSCAL %ZDSCAL %%ZGEMM %ZGEMM %%ZGEMV %ZGEMV %%ZSCAL %ZSCAL))

(CFFI:DEFCFUN ("caxpy_" %%CAXPY :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (N :POINTER)
  (CA :POINTER)
  (CX :POINTER)
  (INCX :POINTER)
  (CY :POINTER)
  (INCY :POINTER))

(COMMON-LISP:DEFUN %CAXPY (N CA CX INCX CY INCY)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%CAXPY)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT) CA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        CX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        CY)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCY))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF3401 ':INT32)
                              (CA-REF3402
                               'MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
                              (INCX-REF3404 ':INT32) (INCY-REF3406 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3401 :INT32) N)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              CA-REF3402 MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART CA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART CA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF3404 :INT32) INCX)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCY-REF3406 :INT32) INCY)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((CX-REF3403 CX) (CY-REF3405 CY))
      (%%CAXPY N-REF3401 CA-REF3402 CX-REF3403 INCX-REF3404 CY-REF3405
       INCY-REF3406))))

(CFFI:DEFCFUN ("cgemm_" %%CGEMM :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (TRANSA :STRING)
  (TRANSB :STRING)
  (M :POINTER)
  (N :POINTER)
  (K :POINTER)
  (ALPHA :POINTER)
  (A :POINTER)
  (LDA :POINTER)
  (B :POINTER)
  (LDB :POINTER)
  (BETA :POINTER)
  (C :POINTER)
  (LDC :POINTER))

(COMMON-LISP:DEFUN %CGEMM (TRANSA TRANSB M N K ALPHA A LDA B LDB BETA C LDC)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%CGEMM)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANSA)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANSB)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) K)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT) ALPHA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        A)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        B)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDB)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT) BETA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        C)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDC))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF3409 ':INT32) (N-REF3410 ':INT32)
                              (K-REF3411 ':INT32)
                              (ALPHA-REF3412
                               'MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
                              (LDA-REF3414 ':INT32) (LDB-REF3416 ':INT32)
                              (BETA-REF3417
                               'MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
                              (LDC-REF3419 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF3409 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3410 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF K-REF3411 :INT32) K)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              ALPHA-REF3412
                              MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART ALPHA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART ALPHA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF LDA-REF3414 :INT32) LDA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDB-REF3416 :INT32) LDB)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              BETA-REF3417
                              MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART BETA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART BETA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF LDC-REF3419 :INT32) LDC)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((A-REF3413 A) (B-REF3415 B)
                                            (C-REF3418 C))
      (%%CGEMM TRANSA TRANSB M-REF3409 N-REF3410 K-REF3411 ALPHA-REF3412
       A-REF3413 LDA-REF3414 B-REF3415 LDB-REF3416 BETA-REF3417 C-REF3418
       LDC-REF3419))))

(CFFI:DEFCFUN ("cgemv_" %%CGEMV :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (TRANS :STRING)
  (M :POINTER)
  (N :POINTER)
  (ALPHA :POINTER)
  (A :POINTER)
  (LDA :POINTER)
  (X :POINTER)
  (INCX :POINTER)
  (BETA :POINTER)
  (Y :POINTER)
  (INCY :POINTER))

(COMMON-LISP:DEFUN %CGEMV (TRANS M N ALPHA A LDA X INCX BETA Y INCY)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%CGEMV)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT) ALPHA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        A)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        X)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT) BETA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        Y)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCY))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF3421 ':INT32) (N-REF3422 ':INT32)
                              (ALPHA-REF3423
                               'MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
                              (LDA-REF3425 ':INT32) (INCX-REF3427 ':INT32)
                              (BETA-REF3428
                               'MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
                              (INCY-REF3430 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF3421 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3422 :INT32) N)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              ALPHA-REF3423
                              MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART ALPHA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART ALPHA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF LDA-REF3425 :INT32) LDA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF3427 :INT32) INCX)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              BETA-REF3428
                              MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART BETA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART BETA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF INCY-REF3430 :INT32) INCY)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((A-REF3424 A) (X-REF3426 X)
                                            (Y-REF3429 Y))
      (%%CGEMV TRANS M-REF3421 N-REF3422 ALPHA-REF3423 A-REF3424 LDA-REF3425
       X-REF3426 INCX-REF3427 BETA-REF3428 Y-REF3429 INCY-REF3430))))

(CFFI:DEFCFUN ("cscal_" %%CSCAL :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (N :POINTER)
  (CA :POINTER)
  (CX :POINTER)
  (INCX :POINTER))

(COMMON-LISP:DEFUN %CSCAL (N CA CX INCX)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%CSCAL)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT) CA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        CX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF3431 ':INT32)
                              (CA-REF3432
                               'MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
                              (INCX-REF3434 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3431 :INT32) N)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              CA-REF3432 MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART CA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART CA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF3434 :INT32) INCX)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((CX-REF3433 CX))
      (%%CSCAL N-REF3431 CA-REF3432 CX-REF3433 INCX-REF3434))))

(CFFI:DEFCFUN ("csscal_" %%CSSCAL :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (N :POINTER)
  (SA :POINTER)
  (CX :POINTER)
  (INCX :POINTER))

(COMMON-LISP:DEFUN %CSSCAL (N SA CX INCX)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%CSSCAL)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE COMMON-LISP:SINGLE-FLOAT SA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        CX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF3435 ':INT32) (SA-REF3436 ':FLOAT)
                              (INCX-REF3438 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3435 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF SA-REF3436 :FLOAT) SA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF3438 :INT32) INCX)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((CX-REF3437 CX))
      (%%CSSCAL N-REF3435 SA-REF3436 CX-REF3437 INCX-REF3438))))

(CFFI:DEFCFUN ("daxpy_" %%DAXPY :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (N :POINTER)
  (DA :POINTER)
  (DX :POINTER)
  (INCX :POINTER)
  (DY :POINTER)
  (INCY :POINTER))

(COMMON-LISP:DEFUN %DAXPY (N DA DX INCX DY INCY)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DAXPY)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT DA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) DX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) DY)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCY))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF3439 ':INT32) (DA-REF3440 ':DOUBLE)
                              (INCX-REF3442 ':INT32) (INCY-REF3444 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3439 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF DA-REF3440 :DOUBLE) DA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF3442 :INT32) INCX)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCY-REF3444 :INT32) INCY)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((DX-REF3441 DX) (DY-REF3443 DY))
      (%%DAXPY N-REF3439 DA-REF3440 DX-REF3441 INCX-REF3442 DY-REF3443
       INCY-REF3444))))

(CFFI:DEFCFUN ("dgemm_" %%DGEMM :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (TRANSA :STRING)
  (TRANSB :STRING)
  (M :POINTER)
  (N :POINTER)
  (K :POINTER)
  (ALPHA :POINTER)
  (A :POINTER)
  (LDA :POINTER)
  (B :POINTER)
  (LDB :POINTER)
  (BETA :POINTER)
  (C :POINTER)
  (LDC :POINTER))

(COMMON-LISP:DEFUN %DGEMM (TRANSA TRANSB M N K ALPHA A LDA B LDB BETA C LDC)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DGEMM)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANSA)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANSB)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) K)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT ALPHA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) A)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) B)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDB)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT BETA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) C)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDC))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF3447 ':INT32) (N-REF3448 ':INT32)
                              (K-REF3449 ':INT32) (ALPHA-REF3450 ':DOUBLE)
                              (LDA-REF3452 ':INT32) (LDB-REF3454 ':INT32)
                              (BETA-REF3455 ':DOUBLE) (LDC-REF3457 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF3447 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3448 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF K-REF3449 :INT32) K)
    (COMMON-LISP:SETF (CFFI:MEM-REF ALPHA-REF3450 :DOUBLE) ALPHA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDA-REF3452 :INT32) LDA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDB-REF3454 :INT32) LDB)
    (COMMON-LISP:SETF (CFFI:MEM-REF BETA-REF3455 :DOUBLE) BETA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDC-REF3457 :INT32) LDC)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((A-REF3451 A) (B-REF3453 B)
                                            (C-REF3456 C))
      (%%DGEMM TRANSA TRANSB M-REF3447 N-REF3448 K-REF3449 ALPHA-REF3450
       A-REF3451 LDA-REF3452 B-REF3453 LDB-REF3454 BETA-REF3455 C-REF3456
       LDC-REF3457))))

(CFFI:DEFCFUN ("dgemv_" %%DGEMV :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (TRANS :STRING)
  (M :POINTER)
  (N :POINTER)
  (ALPHA :POINTER)
  (A :POINTER)
  (LDA :POINTER)
  (X :POINTER)
  (INCX :POINTER)
  (BETA :POINTER)
  (Y :POINTER)
  (INCY :POINTER))

(COMMON-LISP:DEFUN %DGEMV (TRANS M N ALPHA A LDA X INCX BETA Y INCY)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DGEMV)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT ALPHA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) A)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) X)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT BETA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) Y)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCY))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF3459 ':INT32) (N-REF3460 ':INT32)
                              (ALPHA-REF3461 ':DOUBLE) (LDA-REF3463 ':INT32)
                              (INCX-REF3465 ':INT32) (BETA-REF3466 ':DOUBLE)
                              (INCY-REF3468 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF3459 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3460 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF ALPHA-REF3461 :DOUBLE) ALPHA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDA-REF3463 :INT32) LDA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF3465 :INT32) INCX)
    (COMMON-LISP:SETF (CFFI:MEM-REF BETA-REF3466 :DOUBLE) BETA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCY-REF3468 :INT32) INCY)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((A-REF3462 A) (X-REF3464 X)
                                            (Y-REF3467 Y))
      (%%DGEMV TRANS M-REF3459 N-REF3460 ALPHA-REF3461 A-REF3462 LDA-REF3463
       X-REF3464 INCX-REF3465 BETA-REF3466 Y-REF3467 INCY-REF3468))))

(CFFI:DEFCFUN ("dscal_" %%DSCAL :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (N :POINTER)
  (DA :POINTER)
  (DX :POINTER)
  (INCX :POINTER))

(COMMON-LISP:DEFUN %DSCAL (N DA DX INCX)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DSCAL)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT DA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) DX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF3469 ':INT32) (DA-REF3470 ':DOUBLE)
                              (INCX-REF3472 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3469 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF DA-REF3470 :DOUBLE) DA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF3472 :INT32) INCX)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((DX-REF3471 DX))
      (%%DSCAL N-REF3469 DA-REF3470 DX-REF3471 INCX-REF3472))))

(CFFI:DEFCFUN ("saxpy_" %%SAXPY :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (N :POINTER)
  (SA :POINTER)
  (SX :POINTER)
  (INCX :POINTER)
  (SY :POINTER)
  (INCY :POINTER))

(COMMON-LISP:DEFUN %SAXPY (N SA SX INCX SY INCY)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%SAXPY)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE COMMON-LISP:SINGLE-FLOAT SA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) SX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) SY)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCY))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF3473 ':INT32) (SA-REF3474 ':FLOAT)
                              (INCX-REF3476 ':INT32) (INCY-REF3478 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3473 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF SA-REF3474 :FLOAT) SA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF3476 :INT32) INCX)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCY-REF3478 :INT32) INCY)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((SX-REF3475 SX) (SY-REF3477 SY))
      (%%SAXPY N-REF3473 SA-REF3474 SX-REF3475 INCX-REF3476 SY-REF3477
       INCY-REF3478))))

(CFFI:DEFCFUN ("sgemm_" %%SGEMM :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (TRANSA :STRING)
  (TRANSB :STRING)
  (M :POINTER)
  (N :POINTER)
  (K :POINTER)
  (ALPHA :POINTER)
  (A :POINTER)
  (LDA :POINTER)
  (B :POINTER)
  (LDB :POINTER)
  (BETA :POINTER)
  (C :POINTER)
  (LDC :POINTER))

(COMMON-LISP:DEFUN %SGEMM (TRANSA TRANSB M N K ALPHA A LDA B LDB BETA C LDC)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%SGEMM)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANSA)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANSB)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) K)
                       (COMMON-LISP:TYPE COMMON-LISP:SINGLE-FLOAT ALPHA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) A)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) B)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDB)
                       (COMMON-LISP:TYPE COMMON-LISP:SINGLE-FLOAT BETA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) C)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDC))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF3481 ':INT32) (N-REF3482 ':INT32)
                              (K-REF3483 ':INT32) (ALPHA-REF3484 ':FLOAT)
                              (LDA-REF3486 ':INT32) (LDB-REF3488 ':INT32)
                              (BETA-REF3489 ':FLOAT) (LDC-REF3491 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF3481 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3482 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF K-REF3483 :INT32) K)
    (COMMON-LISP:SETF (CFFI:MEM-REF ALPHA-REF3484 :FLOAT) ALPHA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDA-REF3486 :INT32) LDA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDB-REF3488 :INT32) LDB)
    (COMMON-LISP:SETF (CFFI:MEM-REF BETA-REF3489 :FLOAT) BETA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDC-REF3491 :INT32) LDC)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((A-REF3485 A) (B-REF3487 B)
                                            (C-REF3490 C))
      (%%SGEMM TRANSA TRANSB M-REF3481 N-REF3482 K-REF3483 ALPHA-REF3484
       A-REF3485 LDA-REF3486 B-REF3487 LDB-REF3488 BETA-REF3489 C-REF3490
       LDC-REF3491))))

(CFFI:DEFCFUN ("sgemv_" %%SGEMV :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (TRANS :STRING)
  (M :POINTER)
  (N :POINTER)
  (ALPHA :POINTER)
  (A :POINTER)
  (LDA :POINTER)
  (X :POINTER)
  (INCX :POINTER)
  (BETA :POINTER)
  (Y :POINTER)
  (INCY :POINTER))

(COMMON-LISP:DEFUN %SGEMV (TRANS M N ALPHA A LDA X INCX BETA Y INCY)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%SGEMV)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE COMMON-LISP:SINGLE-FLOAT ALPHA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) A)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) X)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX)
                       (COMMON-LISP:TYPE COMMON-LISP:SINGLE-FLOAT BETA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) Y)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCY))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF3493 ':INT32) (N-REF3494 ':INT32)
                              (ALPHA-REF3495 ':FLOAT) (LDA-REF3497 ':INT32)
                              (INCX-REF3499 ':INT32) (BETA-REF3500 ':FLOAT)
                              (INCY-REF3502 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF3493 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3494 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF ALPHA-REF3495 :FLOAT) ALPHA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDA-REF3497 :INT32) LDA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF3499 :INT32) INCX)
    (COMMON-LISP:SETF (CFFI:MEM-REF BETA-REF3500 :FLOAT) BETA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCY-REF3502 :INT32) INCY)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((A-REF3496 A) (X-REF3498 X)
                                            (Y-REF3501 Y))
      (%%SGEMV TRANS M-REF3493 N-REF3494 ALPHA-REF3495 A-REF3496 LDA-REF3497
       X-REF3498 INCX-REF3499 BETA-REF3500 Y-REF3501 INCY-REF3502))))

(CFFI:DEFCFUN ("sscal_" %%SSCAL :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (N :POINTER)
  (SA :POINTER)
  (SX :POINTER)
  (INCX :POINTER))

(COMMON-LISP:DEFUN %SSCAL (N SA SX INCX)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%SSCAL)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE COMMON-LISP:SINGLE-FLOAT SA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) SX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF3503 ':INT32) (SA-REF3504 ':FLOAT)
                              (INCX-REF3506 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3503 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF SA-REF3504 :FLOAT) SA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF3506 :INT32) INCX)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((SX-REF3505 SX))
      (%%SSCAL N-REF3503 SA-REF3504 SX-REF3505 INCX-REF3506))))

(CFFI:DEFCFUN ("zaxpy_" %%ZAXPY :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (N :POINTER)
  (ZA :POINTER)
  (ZX :POINTER)
  (INCX :POINTER)
  (ZY :POINTER)
  (INCY :POINTER))

(COMMON-LISP:DEFUN %ZAXPY (N ZA ZX INCX ZY INCY)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZAXPY)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT) ZA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        ZX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        ZY)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCY))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF3507 ':INT32)
                              (ZA-REF3508
                               'MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
                              (INCX-REF3510 ':INT32) (INCY-REF3512 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3507 :INT32) N)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              ZA-REF3508 MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART ZA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART ZA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF3510 :INT32) INCX)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCY-REF3512 :INT32) INCY)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((ZX-REF3509 ZX) (ZY-REF3511 ZY))
      (%%ZAXPY N-REF3507 ZA-REF3508 ZX-REF3509 INCX-REF3510 ZY-REF3511
       INCY-REF3512))))

(CFFI:DEFCFUN ("zdscal_" %%ZDSCAL :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (N :POINTER)
  (DA :POINTER)
  (ZX :POINTER)
  (INCX :POINTER))

(COMMON-LISP:DEFUN %ZDSCAL (N DA ZX INCX)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZDSCAL)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT DA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        ZX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF3513 ':INT32) (DA-REF3514 ':DOUBLE)
                              (INCX-REF3516 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3513 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF DA-REF3514 :DOUBLE) DA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF3516 :INT32) INCX)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((ZX-REF3515 ZX))
      (%%ZDSCAL N-REF3513 DA-REF3514 ZX-REF3515 INCX-REF3516))))

(CFFI:DEFCFUN ("zgemm_" %%ZGEMM :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (TRANSA :STRING)
  (TRANSB :STRING)
  (M :POINTER)
  (N :POINTER)
  (K :POINTER)
  (ALPHA :POINTER)
  (A :POINTER)
  (LDA :POINTER)
  (B :POINTER)
  (LDB :POINTER)
  (BETA :POINTER)
  (C :POINTER)
  (LDC :POINTER))

(COMMON-LISP:DEFUN %ZGEMM (TRANSA TRANSB M N K ALPHA A LDA B LDB BETA C LDC)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZGEMM)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANSA)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANSB)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) K)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT) ALPHA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        A)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        B)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDB)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT) BETA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        C)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDC))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF3519 ':INT32) (N-REF3520 ':INT32)
                              (K-REF3521 ':INT32)
                              (ALPHA-REF3522
                               'MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
                              (LDA-REF3524 ':INT32) (LDB-REF3526 ':INT32)
                              (BETA-REF3527
                               'MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
                              (LDC-REF3529 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF3519 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3520 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF K-REF3521 :INT32) K)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              ALPHA-REF3522
                              MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART ALPHA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART ALPHA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF LDA-REF3524 :INT32) LDA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDB-REF3526 :INT32) LDB)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              BETA-REF3527
                              MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART BETA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART BETA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF LDC-REF3529 :INT32) LDC)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((A-REF3523 A) (B-REF3525 B)
                                            (C-REF3528 C))
      (%%ZGEMM TRANSA TRANSB M-REF3519 N-REF3520 K-REF3521 ALPHA-REF3522
       A-REF3523 LDA-REF3524 B-REF3525 LDB-REF3526 BETA-REF3527 C-REF3528
       LDC-REF3529))))

(CFFI:DEFCFUN ("zgemv_" %%ZGEMV :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (TRANS :STRING)
  (M :POINTER)
  (N :POINTER)
  (ALPHA :POINTER)
  (A :POINTER)
  (LDA :POINTER)
  (X :POINTER)
  (INCX :POINTER)
  (BETA :POINTER)
  (Y :POINTER)
  (INCY :POINTER))

(COMMON-LISP:DEFUN %ZGEMV (TRANS M N ALPHA A LDA X INCX BETA Y INCY)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZGEMV)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT) ALPHA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        A)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        X)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT) BETA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        Y)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCY))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF3531 ':INT32) (N-REF3532 ':INT32)
                              (ALPHA-REF3533
                               'MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
                              (LDA-REF3535 ':INT32) (INCX-REF3537 ':INT32)
                              (BETA-REF3538
                               'MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
                              (INCY-REF3540 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF3531 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3532 :INT32) N)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              ALPHA-REF3533
                              MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART ALPHA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART ALPHA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF LDA-REF3535 :INT32) LDA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF3537 :INT32) INCX)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              BETA-REF3538
                              MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART BETA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART BETA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF INCY-REF3540 :INT32) INCY)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((A-REF3534 A) (X-REF3536 X)
                                            (Y-REF3539 Y))
      (%%ZGEMV TRANS M-REF3531 N-REF3532 ALPHA-REF3533 A-REF3534 LDA-REF3535
       X-REF3536 INCX-REF3537 BETA-REF3538 Y-REF3539 INCY-REF3540))))

(CFFI:DEFCFUN ("zscal_" %%ZSCAL :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBBLAS)
    :VOID
  (N :POINTER)
  (ZA :POINTER)
  (ZX :POINTER)
  (INCX :POINTER))

(COMMON-LISP:DEFUN %ZSCAL (N ZA ZX INCX)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZSCAL)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT) ZA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        ZX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF3541 ':INT32)
                              (ZA-REF3542
                               'MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
                              (INCX-REF3544 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF3541 :INT32) N)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              ZA-REF3542 MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART ZA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART ZA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF3544 :INT32) INCX)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((ZX-REF3543 ZX))
      (%%ZSCAL N-REF3541 ZA-REF3542 ZX-REF3543 INCX-REF3544))))

(COMMON-LISP:DECLAIM
 (COMMON-LISP:NOTINLINE %%CAXPY %CAXPY %%CGEMM %CGEMM %%CGEMV %CGEMV %%CSCAL
  %CSCAL %%CSSCAL %CSSCAL %%DAXPY %DAXPY %%DGEMM %DGEMM %%DGEMV %DGEMV %%DSCAL
  %DSCAL %%SAXPY %SAXPY %%SGEMM %SGEMM %%SGEMV %SGEMV %%SSCAL %SSCAL %%ZAXPY
  %ZAXPY %%ZDSCAL %ZDSCAL %%ZGEMM %ZGEMM %%ZGEMV %ZGEMV %%ZSCAL %ZSCAL))

(MAGICL.FOREIGN-LIBRARIES:TRACK-SYMBOLS 'MAGICL.FOREIGN-LIBRARIES::LIBBLAS
                                        '(("CAXPY" "caxpy_" %%CAXPY %CAXPY)
                                          ("CGEMM" "cgemm_" %%CGEMM %CGEMM)
                                          ("CGEMV" "cgemv_" %%CGEMV %CGEMV)
                                          ("CSCAL" "cscal_" %%CSCAL %CSCAL)
                                          ("CSSCAL" "csscal_" %%CSSCAL %CSSCAL)
                                          ("DAXPY" "daxpy_" %%DAXPY %DAXPY)
                                          ("DGEMM" "dgemm_" %%DGEMM %DGEMM)
                                          ("DGEMV" "dgemv_" %%DGEMV %DGEMV)
                                          ("DSCAL" "dscal_" %%DSCAL %DSCAL)
                                          ("SAXPY" "saxpy_" %%SAXPY %SAXPY)
                                          ("SGEMM" "sgemm_" %%SGEMM %SGEMM)
                                          ("SGEMV" "sgemv_" %%SGEMV %SGEMV)
                                          ("SSCAL" "sscal_" %%SSCAL %SSCAL)
                                          ("ZAXPY" "zaxpy_" %%ZAXPY %ZAXPY)
                                          ("ZDSCAL" "zdscal_" %%ZDSCAL %ZDSCAL)
                                          ("ZGEMM" "zgemm_" %%ZGEMM %ZGEMM)
                                          ("ZGEMV" "zgemv_" %%ZGEMV %ZGEMV)
                                          ("ZSCAL" "zscal_" %%ZSCAL %ZSCAL)))

(COMMON-LISP:EXPORT
 '(%CAXPY %CGEMM %CGEMV %CSCAL %CSSCAL %DAXPY %DGEMM %DGEMV %DSCAL %SAXPY
   %SGEMM %SGEMV %SSCAL %ZAXPY %ZDSCAL %ZGEMM %ZGEMV %ZSCAL)
 '#:MAGICL.BLAS-CFFI)

;;; End of file.
